### ISSUE TITLE
pamfingerprint and pyfingerprint not found

### ISSUE THREAD

**Issue by Luxi84** [philippmeisberger/pam-fingerprint#1]
Hallo I used different installation Methods and tryed in Debian 10 and Ubuntu 19.04,
but wehn I use the PAM then pamfingerprint is not found (also pyfingerprint will not be found if I uncomment the import of pamfingerprint) I know that I have to remove the first pyfingerprint. at the Import.
In the built Debian Packages or from the Repository there is no pamfingerprint.py File (Modul to Import) and also no pyfingerprint.py and I beleave pam_fingerprint.py wont import itself as Module.
I was using Version 1.5.
The Fingerprintsensor works (enroling, checking and so on) but the PAM does not.
Under Ubuntu 19.04 Python 2.7 is used, Python 3.x doesent change this.

Can you please help me?

**Comment by philippmeisberger** [comment]
Hi,
thanks for your report. There is something weird with Python 2 package path under Debian 10/Ubuntu 19.04 inside the PAM module. I possibly found a fix for that. Could you please try out the fix on the branch https://github.com/philippmeisberger/pam-fingerprint/tree/Bugfix/1-fix-python-import if your problems are gone? If so I immediately release a new version ;)

**Comment by Luxi84** [comment]
Hi I could solve the Issue by
import sys
and
sys.path.append('/usr/lib/python2.7/dist-packages/')
in the pam-fingerprint.py

I am not sure why the searchpaths are not set maybe an error with my env/config.
I sat more than one day to figure it out...
Now it works :)

thanks for your supply
Regarts Martin (also from Germany like you I think ^^ ?)
